services:
  - type: worker
    name: mega-mind-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: BOT_NAME
        value: MEGA MIND
      - key: OWNER_NUMBER
        sync: false
      - key: SESSION_ID
        sync: false
      - key: SESSION_SERVER_URL
        value: https://mega-mind-sessions.onrender.com
      - key: AUTO_FETCH_SESSION
        value: "false"
      - key: PREFIX
        value: "."
      - key: MODE
        value: public
